AddCSLuaFile()

DarkRP.createCategory{
    name = "Medical Corp",
    categorises = "jobs",
    startExpanded = true,
    color = Color(0, 255, 127),
    canSee = function(ply) return true end,
    sortOrder = 3,
}

TEAM_medic = DarkRP.createJob("Medical Trooper", {
    color = Color(0, 255, 127),
    model = {"models/nada/male/MedicalTrooper.mdl", "models/nada/female/MedicalTrooper.mdl"},
    description = [[combat medic personnel of the Imperial Army who were responsible for providing first aid and frontline trauma care on the battlefield for the Galactic Empire.]],
    weapons = {"masita_e105d", "masita_rk3","weapon_bactainjector", "arccw_bacta_grenade"},
    command = "medic",
    max = 0,
    salary = 100,
    admin = 0,
    vote = false,
    hasLicense = false,
    canDemote = true,
    category = "Medical Corp",
    PlayerSpawn = EYNJobStats( 200, 100 ),
    sortOrder = 3,
}) 
TEAM_medicevo = DarkRP.createJob("Medical EVO Trooper", {
    color = Color(0, 255, 127),
    model = {"models/player/sample/evo/evo.mdl"},
    description = [[They are highly specialized and crucial for handling dangerous biological materials and unknown substances or organisms of extraterrestrial origin.]],
    weapons = {"masita_e22", "masita_a180_pistol", "weapon_bactainjector", "weapon_bactanade", "arccw_bacta_grenade"},
    command = "medicevo",
    max = 0,
    salary = 150,
    admin = 0,
    vote = false,
    hasLicense = false,
    canDemote = true,
    category = "Medical Corp",
    PlayerSpawn = EYNJobStats( 200, 150 ),
    sortOrder = 4,
}) 
TEAM_medicflame = DarkRP.createJob("Medical Flame Trooper", {
    color = Color(0, 255, 127),
    model = {"models/nada/FlameTrooper.mdl"},
    description = [[flame unit are centered around the specialized and critical role of addressing and managing and purging biological hazards.]],
    weapons = {"masita_e105d", "masita_rk3", "weapon_imperial_flamethrower", "weapon_bactainjector", "weapon_bactanade", "arccw_bacta_grenade"},
    command = "medicflame",
    max = 0,
    salary = 150,
    admin = 0,
    vote = false,
    hasLicense = false,
    canDemote = true,
    category = "Medical Corp",
    PlayerSpawn = EYNJobStats( 200, 150 ),
    sortOrder = 5,
})
TEAM_medicfr = DarkRP.createJob("Medical Field Rescue Trooper", {
    color = Color(0, 255, 127),
    model = {"models/nada/male/MedicalTrooper.mdl", "models/nada/female/MedicalTrooper.mdl"},
    description = [[Field rescue medics play a pivotal role in providing immediate and life-saving care in challenging and dynamic environments.]],
    weapons = {"masita_e105d", "masita_rk3","weapon_bactainjector", "arccw_bacta_grenade"},
    command = "medicfr",
    max = 0,
    salary = 150,
    admin = 0,
    vote = false,
    hasLicense = false,
    canDemote = true,
    category = "Medical Corp",
    PlayerSpawn = EYNJobStats( 200, 150 ),
    sortOrder = 6,
}) 
TEAM_mediccmdr = DarkRP.createJob("Medical Commander", {
    color = Color(0, 255, 127),
    model = {"models/nada/male/MedicalTrooper.mdl", "models/nada/female/MedicalTrooper.mdl"},
    description = [[Commander for the Imperial Medical Battalion.]],
    weapons = {"masita_e105d", "masita_blurrg", "weapon_bactainjector", "weapon_bactanade", "arccw_bacta_grenade"},
    command = "mediccmdr",
    max = 0,
    salary = 250,
    admin = 0,
    vote = false,
    hasLicense = false,
    canDemote = true,
    category = "Medical Corp",
    PlayerSpawn = EYNJobStats( 300, 200 ),
    sortOrder = 7,
})